export {
  SIGNAKIT_CDN_URL,
  DEFAULT_POLLING_INTERVAL,
  SIGNAKIT_EVENTS_URL,
  BUCKET_SPACE,
  MAX_EVENT_KEY_LENGTH,
  MAX_USER_ID_LENGTH,
  MAX_METADATA_SIZE_BYTES,
  MAX_ATTRIBUTES_COUNT,
  MAX_ATTRIBUTE_KEY_LENGTH,
  MAX_ATTRIBUTE_VALUE_LENGTH,
} from '@signakit/flags-core'
